# ~/.cloudflared/config.yml
tunnel: 07127b2c-23f0-4088-b66f-68b5f92025d7

ingress:
  - hostname: gameapp.raysosglobal.com
    service: http://localhost:18080

  - hostname: app.raysosglobal.com
    service: http://localhost:18080

  - hostname: grafana.raysosglobal.com
    service: http://localhost:18080

  - hostname: prometheus.raysosglobal.com
    service: http://localhost:18080

  - hostname: argocd.raysosglobal.com
    service: http://localhost:18080

  - service: http_status:404
